[versions]

[libraries]
spring-boot-starter-webmvc = { group = "org.springframework.boot", name = "spring-boot-starter-webmvc" }
spring-boot-starter-validation = { group = "org.springframework.boot", name = "spring-boot-starter-validation" }
spring-boot-starter-webmvc-test = { group = "org.springframework.boot", name = "spring-boot-starter-webmvc-test" }
spring-boot-starter-validation-test = { group = "org.springframework.boot", name = "spring-boot-starter-validation-test" }
junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher" }
org-openapi-generator-gradle-plugin = { group = "org.openapi.generator", name = "org.openapi.generator.gradle.plugin", version = "7.25.0" }
springdoc-openapi-starter-webmvc-ui = { group = "org.springdoc", name = "springdoc-openapi-starter-webmvc-ui", version = "3.1.0" }

[plugins]
org-springframework-boot = { id = "org.springframework.boot", version = "4.1.1" }
io-spring-dependency-management = { id = "io.spring.dependency-management", version = "1.1.7" }


[bundles]
server-implementation = [
    "spring-boot-starter-webmvc",
    "spring-boot-starter-validation",
    "springdoc-openapi-starter-webmvc-ui"
]
server-testImplementation = [
    "spring-boot-starter-webmvc-test",
    "spring-boot-starter-validation-test"
]
server-testRuntimeOnly = [
    "junit-platform-launcher"
]