[versions]
spring-boot = "4.1.1"

[plugins]

[libraries]
openapi-generator-gradle-plugin = { group = "org.openapi.generator", name = "org.openapi.generator.gradle.plugin", version = "7.25.0" }
spring-boot-dependencies = { group = "org.springframework.boot", name = "spring-boot-dependencies", version.ref = "spring-boot" }
spring-boot-starter-webmvc = { group = "org.springframework.boot", name = "spring-boot-starter-webmvc" }
spring-boot-starter-webmvc-test = { group = "org.springframework.boot", name = "spring-boot-starter-webmvc-test" }
spring-boot-starter-validation = { group = "org.springframework.boot", name = "spring-boot-starter-validation" }
spring-boot-starter-validation-test = { group = "org.springframework.boot", name = "spring-boot-starter-validation-test" }
springdoc-openapi-starter-webmvc-ui = { group = "org.springdoc", name = "springdoc-openapi-starter-webmvc-ui", version = "3.1.0" }
